repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer # Ensures files end with a newline
      - id: trailing-whitespace # Removes trailing whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-zero-even-if-changed
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.0
    hooks:
      - id: pyproject-fmt # Formats pyproject.toml file
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt # Formats YAML files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint # Lints YAML files
        args: [-c=.yamllint, --no-warnings]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt # Formats shell scripts
